name: Export Notion Student Planner
on:
  schedule:
    - cron: '0 2 * * *'  # Daily at 2 AM
  workflow_dispatch:     # Manual trigger

jobs:
  export:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Remove previous export (optional, keeps only latest files)
      - run: rm -rf student-planner/

      # Export from Notion
      - uses: Gabriella439/notion-to-markdown@main
        with:
          notion-token: ${{ secrets.NOTION_TOKEN }}

      # Clean filenames and folders (removes UUIDs)
      - name: Clean filenames and folders after export
        run: python3 "export cleaner/clean_notion_export.py"

      # Commit and push changes
      - uses: EndBug/add-and-commit@v9
        with:
          add: 'student-planner/'
          message: 'Auto-export from Notion'
