name: Export Notion Student Planner
on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:
  export:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - run: rm -rf student-planner/

      - uses: Gabriella439/notion-to-markdown@main
        with:
          notion-token: ${{ secrets.NOTION_TOKEN }}
          output: "student-planner"  # if supported

      # If output argument is not supported, add this:
      # - name: Move export to student-planner
      #   run: |
      #     export_dir=$(find . -maxdepth 1 -type d -name "Export*" | head -n1)
      #     if [ -n "$export_dir" ]; then
      #       mv "$export_dir" student-planner
      #     fi

      - name: Clean filenames and folders
        run: python3 "export cleaner/clean_notion_export.py"

      - uses: EndBug/add-and-commit@v9
        with:
          add: 'student-planner/'
          message: 'Auto-export from Notion'
